/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 90ab816190929c03ddd91a73b00f467d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
		MESSAGE_SUMMARY_WORKFLOW: Workflow /* MessageSummaryWorkflow */;
	}
}
interface Env extends Cloudflare.Env {}
